    version: "3"
services:
  hub:
    image: selenium/hub:3.14
    container_name: Selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '512m'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  mseautomation:
    image: docker/msev1
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - REMOTE=true
      - MODULE=testng.xml
      - HUB_HOST=hub
    volumes:
      - ./remote-results:/usr/mystartupEquity/test-output
      - ./Extent-report:/usr/mystartupEquity/Reports



